### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by alanhogan** [th507/npm-shrinkwrap-install#1]
```
$  npm-r some-package --save
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at diff (/Users/ahogan/.nvm/versions/node/v5.7.1/lib/node_modules/npm-shrinkwrap-install/lib/diff-deps.js:4:28)
    at /Users/ahogan/.nvm/versions/node/v5.7.1/lib/node_modules/npm-shrinkwrap-install/bin/install.js:30:21
    at process._tickCallback (node.js:406:9)
```

`some-package` (not the real name) is in my package.json and is currently installed.

Any idea what’s up here? Is `npm-shrinkwrap-install` compatible with `node` 5.7?

**Comment by i-e-b** [comment]
Similar to https://github.com/npm/npm/issues/5109
Looks like the error is here:
https://github.com/npm/npm/commit/a9d9fa5ad3b8c925a589422b7be28d2735f320b0

Try creating an empty "dependencies" object in the package.json?
